# Site settings
title: Aleksey Gladysh
email: aleksey.gladysh@gmail.com
description: >
  Web designer and developer from California. Artist, musician,
  and chef in a past life.
baseurl: ""
url: "http://lyosha.me"

social:
  facebook: https://www.facebook.com/aleksey.gladysh
  linkedin: https://www.linkedin.com/in/alekseyg
  instagram: https://instagram.com/aleksey_g/
  github: https://github.com/alekseyg
  twitter: https://twitter.com/lyosha_g

nav:
# - title: Portfolio
#   url: /portfolio/
# - title: Resume
#   url: /resume/
- title: Blog
  url: /blog/


# Build settings
markdown: kramdown
permalink: pretty
exclude: [Gemfile, Gemfile.lock]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
