# Site settings
title: Aleksey Gladysh
html_title: >
  A<span class="hidden-xs">leksey
  </span>G<span class="hidden-xs">ladysh</span>
email: aleksey.gladysh@gmail.com
description: >
  Web designer and developer from California. Artist, musician,
  and chef in a past life.
baseurl: ""
url: "http://lyosha.me"

google_analytics: UA-10323085-1

social:
  facebook: https://www.facebook.com/aleksey.gladysh
  linkedin: https://www.linkedin.com/in/alekseyg
  instagram: https://instagram.com/aleksey_g/
  github: https://github.com/alekseyg
  twitter: https://twitter.com/lyosha_g

nav:
# - title: Portfolio
#   url: /portfolio/
# - title: Resume
#   url: /resume/
- title: Blog
  url: /blog/


# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
exclude: [Gemfile, Gemfile.lock]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-coffeescript
