# Site settings
title: Aleksey Gladysh
email: aleksey.gladysh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web designer and developer from California. Artist, musician,
  and chef in a past life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lyosha.me" # the base hostname & protocol for your site
twitter_username: lyosha_g
github_username:  alekseyg

# Build settings
markdown: kramdown
permalink: pretty
exclude: [Gemfile, Gemfile.lock]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
